#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


alias ...='sudo -s'

# Begin of line
bindkey '^[[1~'	beginning-of-line
bindkey '^[OH'	beginning-of-line
bindkey '^A'	beginning-of-line

# End of line
bindkey '^[[4~'	end-of-line
bindkey '^[OF'	end-of-line
bindkey '^E'	end-of-line
