#!/bin/sh

if [ ! -d ~/.zprezto ]; then
	echo ".zprezto dir has not been found in user home" > /dev/stderr
	exit 1
fi

echo "Installing zprezto"

for i in ~/.zprezto/runcoms/z*; do
	f=.$(basename $i)
	echo "  x Copying file $f"
	if [ -f ~/$f ]; then
		mv ~/$f ~/$f.pre-zprezto
	fi
	cp $i ~/$f
done

echo "Installation done. Running zsh now"
zsh
